# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: jonohawkins
email: uceeawk@ucl.ac.uk
description: >- # this means to ignore newlines until "baseurl:"
  Postgraduate student at University College London in Ice-Penetrating Radar.  Glaciers, electronics and vertical things.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.jonohawkins.co.uk" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jonohawkins
github_username:  jonodhawkins
author: Jono Hawkins

defaults:
  -
    scope:
      path: ""
    values:
      splash: false
      splash-img: ""
      splash-header: "welcome"
      splash-text: ""
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Jono Hawkins"
      thumbnail: "/assets/img/blog-thumbnail.svg"
      icon: "default"

collections:
  photos:

paginate: 4
paginate_path: "/blog/page-:num/"


markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

plugins:
  - jekyll-paginate

# Build settings
#theme: minima
#plugins:
#  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
